server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location /smart-code-tool {
        alias   /usr/share/nginx/html/smart-code-tool/;
        index  index.html index.htm;
        try_files $uri $uri/ /smart-code-tool/index.html; # 关键：防止 history 刷新 404
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}